### PR TITLE
add background when hovering for visibility

### PR DESCRIPTION
**Pull request by aftadizca**
add background when hovering for visibility

### CODE REVIEW

**Comment by aftadizca** [comment]
add background when hovering for visibility

**Review by n7itro — COMMENTED** [review]
These changes don't appear to work on my device, so I will implement it myself. Thanks for trying to help though!

**Comment by aftadizca** [comment]
work in mine.. but in windows 11

**Comment by aftadizca** [comment]
but your implementation works 🤗 thanks

**Pull request closed without merging**
